project:
  type: website
  output-dir: docs

website:
  title: "Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - publications.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true